name: like_it
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.4.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    path: ^1.9.0
    path_provider: ^2.1.4
    intl: ^0.19.0
    permission_handler: ^11.3.1
    easy_localization: ^3.0.7
    page_transition: ^2.1.0
    flutter_launcher_icons: ^0.13.1
    google_fonts: ^6.2.1
    adaptive_theme: ^3.6.0
    country_code_picker: ^3.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/like_it_icon.png"

flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/translation/
