name: like_it
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.5.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.6
    path: ^1.9.0
    path_provider: ^2.1.4
    intl: ^0.19.0
    permission_handler: ^11.3.1
    easy_localization: ^3.0.7
    page_transition: ^2.1.0
    flutter_launcher_icons: ^0.13.1
    adaptive_theme: ^3.6.0
    outline_gradient_button: ^2.0.1+1
    pin_code_fields: ^8.0.1
    country_pickers: ^3.0.1
    cached_network_image: ^3.4.1
    flutter_svg: ^2.0.10+1
    device_info_plus: ^10.1.2
    curved_navigation_bar: ^1.0.6
    carousel_slider: ^5.0.0
    video_player: ^2.9.1
    flutter_rating_bar: ^4.0.1
    url_launcher: ^6.3.0
    flutter_image_compress: ^2.3.0
    image_picker: ^1.1.2
    photo_view: ^0.15.0
    geolocator: ^13.0.1
    geocoding: ^3.0.0
    map_launcher: ^3.5.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/like_it_icon.png"

flutter:
    uses-material-design: true
    assets:
        - assets/videos/
        - assets/images/
        - assets/images/f_n_b/1/A/
        - assets/images/f_n_b/1/B/
        - assets/images/f_n_b/2/A/
        - assets/images/f_n_b/2/B/
        - assets/images/f_n_b/3/A/
        - assets/images/f_n_b/3/B/
        - assets/images/f_n_b/4/A/
        - assets/images/f_n_b/4/B/
        - assets/images/f_n_b/5/A/
        - assets/images/f_n_b/5/B/
        - assets/images/f_n_b/6/A/
        - assets/images/f_n_b/6/B/
        - assets/images/f_n_b/7/A/
        - assets/images/f_n_b/7/B/
        - assets/images/f_n_b/8/A/
        - assets/images/f_n_b/8/B/
        - assets/images/f_n_b/9/A/
        - assets/images/f_n_b/9/B/
        - assets/images/f_n_b/10/A/
        - assets/images/f_n_b/10/B/
        - assets/translation/
    fonts:
        - family: K2D
          fonts:
              - asset: assets/fonts/K2D-Regular.ttf
                weight: 400
              - asset: assets/fonts/K2D-Bold.ttf
                weight: 700
              - asset: assets/fonts/K2D-Italic.ttf
                style: italic
