flutter_root = `/usr/local/Caskroom/flutter/3.29.0/flutter`
flutter_ios_podfile = File.expand_path("#{flutter_root}/packages/flutter_tools/bin/xcode_backend.rb", __dir__)

if File.exist?(flutter_ios_podfile)
  require flutter_ios_podfile
else
  puts "⚠️  xcode_backend.rb not found! Make sure Flutter is installed correctly."
end

platform :ios, '12.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end


# target 'Runner' do
#   # Comment the next line if you don't want to use dynamic frameworks
#   use_frameworks!

#   # Pods for Runner
#   use_frameworks!
#   use_modular_headers!

#   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

#   target 'RunnerTests' do
#     # inherit! :search_paths
#     Pods for testing
#   end

# end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # You can remove unused permissions here
      # for more infomation: https://github.com/Baseflow/flutter-permission-handler/blob/main/permission_handler_apple/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

        ## dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',
      ]
    end

    if target.name == "geolocator_apple"
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'BYPASS_PERMISSION_LOCATION_ALWAYS=1']
      end
    end

  end
end